[tool.poetry]
name = "seismictools"
version = "0.1.0"
description = ""
authors = ["gasng <kamashev41@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.15"
pyside6 = "^6.10.1"
numpy = "^2.3.5"
segyio = "^1.9.13"
pyqtgraph = "^0.14.0"
scipy = "^1.16.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
Example = 'seismictools.apps.example.main:main'