[tool.poetry]
name = "seismictools"
version = "0.1.0"
description = ""
authors = ["ilyzthe"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.15"
pyside6 = "^6.10.1"
numpy = "^2.3.5"
segyio = "^1.9.13"
pyqtgraph = "^0.14.0"
lasio = "^0.32"
notebook = "^7.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
WLC = 'seismictools.apps.Well_Logging_Classification.main:main'