# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GridWorkerWindow(object):
    def setupUi(self, GridWorkerWindow):
        GridWorkerWindow.setObjectName("GridWorkerWindow")
        GridWorkerWindow.resize(799, 520)
        GridWorkerWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(GridWorkerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.groupBox_load = QtWidgets.QGroupBox(self.splitter_3)
        font = QtGui.QFont()
        font.setBold(True)
        self.groupBox_load.setFont(font)
        self.groupBox_load.setStyleSheet("QPushButton {\n"
"    background-color: rgb(195, 193, 255);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"}\n"
"QGroupBox {\n"
"    background-color: rgb(226, 227, 255);\n"
"    font-weight: bold;\n"
"    color: rgb(35, 35, 35);\n"
"    border: 2px solid #888888;\n"
"    border-radius: 6px;\n"
"    margin-top: 10px;\n"
"    padding: 10px;\n"
"}\n"
"QLabel {\n"
"    color: rgb(60, 60, 200);\n"
"    font-size: 14px;\n"
"}")
        self.groupBox_load.setFlat(False)
        self.groupBox_load.setCheckable(False)
        self.groupBox_load.setObjectName("groupBox_load")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_load)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.groupBox_load)
        self.splitter_2.setStyleSheet("background-color: rgb(226, 227, 255);")
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_filePath = QtWidgets.QLineEdit(self.splitter_2)
        self.lineEdit_filePath.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid #888888;\n"
"border-radius: 6px;\n"
"margin-top: 3 px;\n"
"padding: 3 px;")
        self.lineEdit_filePath.setObjectName("lineEdit_filePath")
        self.verticalLayout.addWidget(self.splitter_2)
        self.splitter = QtWidgets.QSplitter(self.groupBox_load)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.pushButton_load = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.pushButton_load.setFont(font)
        self.pushButton_load.setStyleSheet("")
        self.pushButton_load.setObjectName("pushButton_load")
        self.pushButton_clear = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.verticalLayout.addWidget(self.splitter)
        self.groupBox_select = QtWidgets.QGroupBox(self.splitter_3)
        font = QtGui.QFont()
        font.setBold(True)
        self.groupBox_select.setFont(font)
        self.groupBox_select.setStyleSheet("QPushButton {\n"
"    background-color: rgb(195, 193, 255);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"QGroupBox {\n"
"    background-color: rgb(226, 227, 255);\n"
"    font-weight: bold;\n"
"    color: rgb(35, 35, 35);\n"
"    border: 2px solid #888888;\n"
"    border-radius: 6px;\n"
"    margin-top: 10px;\n"
"    padding: 10px;\n"
"}\n"
"QLabel {\n"
"    color: rgb(60, 60, 200);\n"
"    font-size: 14px;\n"
"}\n"
"")
        self.groupBox_select.setObjectName("groupBox_select")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_select)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter_5 = QtWidgets.QSplitter(self.groupBox_select)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.pushButton_addObject = QtWidgets.QPushButton(self.splitter_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_addObject.setFont(font)
        self.pushButton_addObject.setObjectName("pushButton_addObject")
        self.label_2 = QtWidgets.QLabel(self.splitter_5)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setObjectName("label_2")
        self.listWidget_objects = QtWidgets.QListWidget(self.splitter_5)
        self.listWidget_objects.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid #888888;\n"
"border-radius: 6px;\n"
"margin-top: 3 px;\n"
"padding: 3 px;")
        self.listWidget_objects.setObjectName("listWidget_objects")
        self.verticalLayout_2.addWidget(self.splitter_5)
        self.pushButton_save = QtWidgets.QPushButton(self.splitter_3)
        self.pushButton_save.setStyleSheet("QPushButton {\n"
"    background-color: rgb(192, 187, 255);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-size: 14px;\n"
"}")
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout.addWidget(self.splitter_3)
        self.label_map = QtWidgets.QGraphicsView(self.centralwidget)
        self.label_map.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid #888888;\n"
"border-radius: 6px;\n"
"margin-top: 3 px;\n"
"")
        self.label_map.setObjectName("label_map")
        self.horizontalLayout.addWidget(self.label_map)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        GridWorkerWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(GridWorkerWindow)
        self.statusbar.setObjectName("statusbar")
        GridWorkerWindow.setStatusBar(self.statusbar)

        self.retranslateUi(GridWorkerWindow)
        QtCore.QMetaObject.connectSlotsByName(GridWorkerWindow)

    def retranslateUi(self, GridWorkerWindow):
        _translate = QtCore.QCoreApplication.translate
        GridWorkerWindow.setWindowTitle(_translate("GridWorkerWindow", "Grid Worker"))
        self.groupBox_load.setTitle(_translate("GridWorkerWindow", "Загрузка карты"))
        self.label.setText(_translate("GridWorkerWindow", "Файл:"))
        self.pushButton_load.setText(_translate("GridWorkerWindow", "Загрузить"))
        self.pushButton_clear.setText(_translate("GridWorkerWindow", "Очистить"))
        self.groupBox_select.setTitle(_translate("GridWorkerWindow", "Выделение объектов"))
        self.pushButton_addObject.setText(_translate("GridWorkerWindow", "Добавить объект"))
        self.label_2.setText(_translate("GridWorkerWindow", "<html><head/><body><p align=\"center\">  ТЕКУЩИЕ ОБЪЕКТЫ:</p></body></html>"))
        self.pushButton_save.setText(_translate("GridWorkerWindow", "Сохранить выделенные объекты"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GridWorkerWindow = QtWidgets.QMainWindow()
    ui = Ui_GridWorkerWindow()
    ui.setupUi(GridWorkerWindow)
    GridWorkerWindow.show()
    sys.exit(app.exec_())
